version: "2.3"
services:
  project:
    image: motorai
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ipc: host
    volumes:
      - ${PWD}/:/TechChallange
      - ${DATA}:/TechChallange/data